### POST request to create product
POST http://localhost:8082/api/v1/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Item 1",
  "description": "This is Item 1",
  "price": 23.5,
  "quantity": 10
}

###