service:
  user:
    url: http://localhost:8081
app:
  internal:
    key: wertyuioGHGFDFoiuyfgHJKJLKuiyufdGFHJk
  security:
    jwt:
      secret-key: hhsghsdghggDFGHhjhbBHHbjbhbgfGHJghhjFGHhbjiOklujHJLhlgyLGukdftjresdSytlKGYuhlhgvUkghbVGgvkGVmhgvHKMgvjghVUBhbjbmhgvhGVcjgfgcvgf
      access-token-expiration: 12345678
      refresh-token-expiration: 123456789
server:
  port: 8083