spring:
  application:
    name: api-gateway
app:
  internal:
    key: wertyuioGHGFDFoiuyfgHJKJLKuiyufdGFHJk
  security:
    jwt:
      secret-key: hhsghsdghggDFGHhjhbBHHbjbhbgfGHJghhjFGHhbjiOklujHJLhlgyLGukdftjresdSytlKGYuhlhgvUkghbVGgvkGVmhgvHKMgvjghVUBhbjbmhgvhGVcjgfgcvgf