### POST request to example server
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "email": "test@test.com",
    "firstName": "Olamide",
    "lastName": "Olojede",
    "password": "chris"
}

### POST request to example server
GET http://localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Bearer {{token}}
